rest:
  ssl: false
  host: localhost
  port: 8080
  nameSpace: /server

# Whether to enable Markdown (https://commonmark.org/) and MathJax (https://www.mathjax.org/)
# display in supported metadata fields. By default, only dc.description.abstract is supported.
markdown:
  enabled: true
  mathjax: true
